manifest:
  # remotes:
  #   - name: zmkfirmware
  #     url-base: https://github.com/zmkfirmware
  #   - name: pim447
  #     url-base: https://github.com/cdc-mkb
  #   # Additional modules containing boards/shields/custom code can be listed here as well
  #   # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  # projects:
  #   - name: zmk
  #     remote: zmkfirmware
  #     revision: main
  #     import: app/west.yml
  #   - name: mouse-pim447
  #     remote: pim447
  #     repo-path: zmk
  #     revision: mouse-pim447
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: jgreel
      url-base: https://github.com/jgreel
  projects:
    - name: zmk
      remote: jgreel
      revision: devel-mouse-pim447
      import: app/west.yml
  self:
    path: config
